import type {
  CodexRunDetail,
  CodexRuntimeSnapshot,
  HarnessArtifact,
  HarnessSnapshot,
} from "../types";

const workspace = "/Users/developer/Projects/mobile-app";

function artifact(
  partial: Pick<
    HarnessArtifact,
    "id" | "name" | "kind" | "provider" | "scope" | "path" | "resolution"
  > &
    Partial<HarnessArtifact>,
): HarnessArtifact {
  return {
    relativePath: partial.path.replace(workspace, "."),
    content: null,
    contentHash: partial.id.padEnd(64, "0"),
    modifiedAt: "2026-08-11T06:30:00Z",
    sizeBytes: 2048,
    resolutionReason: "Discovered in the selected workspace.",
    duplicateGroupId: null,
    counterpartId: null,
    description: null,
    sensitive: false,
    truncated: false,
    editable: false,
    editabilityReason: null,
    ...partial,
  };
}

export const sampleSnapshot: HarnessSnapshot = {
  workspacePath: workspace,
  workspaceName: "mobile-app",
  gitBranch: "dev",
  scannedAt: "2026-08-11T06:40:00Z",
  artifacts: [
    artifact({
      id: "rule-global",
      name: "Global AGENTS.md",
      kind: "instructions",
      provider: "codex",
      scope: "user",
      path: "/Users/developer/.codex/AGENTS.md",
      resolution: "effective",
      content: "# Global agreements\n\n- Keep changes reviewable.\n- Verify real behavior before claiming completion.",
      resolutionReason: "Loaded as the global Codex instruction source.",
    }),
    artifact({
      id: "rule-repo",
      name: "Project AGENTS.md",
      kind: "instructions",
      provider: "codex",
      scope: "repo",
      path: `${workspace}/AGENTS.md`,
      resolution: "effective",
      content: "# Project guidance\n\n- Run focused tests after implementation.\n- Keep provider adapters isolated.",
      resolutionReason: "Included after global instructions; project guidance has closer scope.",
    }),
    artifact({
      id: "claude-repo",
      name: "CLAUDE.md",
      kind: "instructions",
      provider: "claude",
      scope: "repo",
      path: `${workspace}/CLAUDE.md`,
      resolution: "defined",
      content: "# Claude project context\n\nUse the shared skills under `.agents/skills`.",
      resolutionReason: "Discovered. Runtime usage has not been observed.",
    }),
    artifact({
      id: "skill-verify",
      name: "verify-pr",
      kind: "skill",
      provider: "shared",
      scope: "repo",
      path: `${workspace}/.agents/skills/verify-pr/SKILL.md`,
      resolution: "effective",
      description: "Run device acceptance and collect evidence for a pull request.",
      content: "---\nname: verify-pr\ndescription: Run device acceptance and collect evidence.\n---\n\n# Verify PR\n\nFollow the case plan and retain evidence.",
      resolutionReason: "Available from the repository skill directory.",
    }),
    artifact({
      id: "skill-qa-codex",
      name: "qa",
      kind: "agent",
      provider: "codex",
      scope: "repo",
      path: `${workspace}/.codex/agents/qa.toml`,
      resolution: "defined",
      counterpartId: "skill-qa-claude",
      content: "name = \"qa\"\nmodel = \"gpt-5.6-terra\"\n",
      resolutionReason: "Discovered Agent definition; runtime registration is not observed yet.",
    }),
    artifact({
      id: "skill-qa-claude",
      name: "qa",
      kind: "agent",
      provider: "claude",
      scope: "repo",
      path: `${workspace}/.claude/agents/qa.md`,
      resolution: "defined",
      counterpartId: "skill-qa-codex",
      content: "# QA agent\n\nInspect app state, execute the case, and retain evidence.",
      resolutionReason: "Discovered Agent definition; runtime registration is not observed yet.",
    }),
    artifact({
      id: "hooks",
      name: "Lifecycle hooks",
      kind: "hook",
      provider: "codex",
      scope: "user",
      path: "/Users/developer/.codex/hooks.json",
      resolution: "effective",
      content: "{\n  \"SessionStart\": [{ \"command\": \"…\" }]\n}",
      resolutionReason: "User hook configuration is enabled.",
      sensitive: true,
    }),
    artifact({
      id: "memory",
      name: "Memory registry",
      kind: "memory",
      provider: "codex",
      scope: "user",
      path: "/Users/developer/.codex/memories/MEMORY.md",
      resolution: "defined",
      content: null,
      resolutionReason: "Metadata only. Expand deliberately to read memory content.",
      sensitive: true,
      sizeBytes: 48000,
      editabilityReason: "Synthetic demo does not access local files.",
    }),
    artifact({
      id: "workflow",
      name: "unattended-issue-dev",
      kind: "workflow",
      provider: "shared",
      scope: "repo",
      path: `${workspace}/.agents/skills/unattended-issue-dev/autodev.workflow.js`,
      resolution: "defined",
      description: "Dev fan-out → device gate → review fan-out → handoff.",
      content: "export const meta = { phases: [\"dev\", \"device\", \"review\", \"handoff\"] };",
      resolutionReason: "Canonical workflow reference; not assumed executable.",
    }),
  ],
  warnings: [
    {
      id: "cross-provider-difference:repo:agent:qa",
      severity: "info",
      title: "Same-name content differs: qa",
      detail: "The Codex and Claude `qa` agents share a name but differ in content.",
      artifactIds: ["skill-qa-codex", "skill-qa-claude"],
    },
  ],
};

export const sampleRuntimeSnapshot: CodexRuntimeSnapshot = {
  state: "connected",
  codexVersion: "codex-cli 0.147.0-demo",
  observedAt: "2026-08-11T06:42:00Z",
  message: "Synthetic browser demo data.",
  skills: [
    {
      name: "verify-pr",
      sourceName: "SKILL.md",
      scope: "repo",
      enabled: true,
    },
    {
      name: "code-review",
      sourceName: "SKILL.md",
      scope: "user",
      enabled: true,
    },
  ],
  hooks: [
    {
      eventName: "SessionStart",
      sourceName: "hooks.json",
      enabled: true,
      trustStatus: "trusted",
    },
  ],
  runs: [
    {
      id: "demo-thread-release-gate",
      title: "Add a verification gate to the release workflow",
      preview: "Inspect the current workflow, add the gate, and retain reviewable evidence.",
      status: "notLoaded",
      source: "vscode",
      createdAt: "2026-08-11T05:48:00Z",
      updatedAt: "2026-08-11T06:31:00Z",
      parentThreadId: null,
      gitBranch: "feat/release-verification",
    },
    {
      id: "demo-thread-hook-audit",
      title: "Audit lifecycle hook coverage",
      preview: "Inventory the configured hooks and identify events without evidence.",
      status: "notLoaded",
      source: "subAgent",
      createdAt: "2026-08-10T09:12:00Z",
      updatedAt: "2026-08-10T09:26:00Z",
      parentThreadId: "demo-parent-thread",
      gitBranch: "dev",
    },
  ],
};

const sampleRunDetails: Record<string, CodexRunDetail> = {
  "demo-thread-release-gate": {
    id: "demo-thread-release-gate",
    title: "Add a verification gate to the release workflow",
    status: "notLoaded",
    turns: [
      {
        id: "demo-turn-1",
        status: "completed",
        startedAt: "2026-08-11T05:48:00Z",
        completedAt: "2026-08-11T06:05:00Z",
        durationMs: 1_020_000,
        stepCount: 4,
      },
      {
        id: "demo-turn-2",
        status: "completed",
        startedAt: "2026-08-11T06:08:00Z",
        completedAt: "2026-08-11T06:31:00Z",
        durationMs: 1_380_000,
        stepCount: 4,
      },
    ],
    steps: [
      {
        id: "demo-step-request",
        turnId: "demo-turn-1",
        kind: "userMessage",
        label: "User request",
        status: null,
        detail: null,
      },
      {
        id: "demo-step-reasoning",
        turnId: "demo-turn-1",
        kind: "reasoning",
        label: "Reasoning",
        status: null,
        detail: null,
      },
      {
        id: "demo-step-search",
        turnId: "demo-turn-1",
        kind: "mcpToolCall",
        label: "MCP tool call",
        status: "completed",
        detail: "Tool: github.search",
      },
      {
        id: "demo-step-agent",
        turnId: "demo-turn-1",
        kind: "subAgentActivity",
        label: "Subagent activity",
        status: "completed",
        detail: "Agent: verifier",
      },
      {
        id: "demo-step-change",
        turnId: "demo-turn-2",
        kind: "fileChange",
        label: "File changes",
        status: "completed",
        detail: "3 changed file(s)",
      },
      {
        id: "demo-step-command",
        turnId: "demo-turn-2",
        kind: "commandExecution",
        label: "Command execution",
        status: "completed",
        detail: "Exit code: 0",
      },
      {
        id: "demo-step-review",
        turnId: "demo-turn-2",
        kind: "enteredReviewMode",
        label: "Review started",
        status: null,
        detail: null,
      },
      {
        id: "demo-step-review-done",
        turnId: "demo-turn-2",
        kind: "exitedReviewMode",
        label: "Review completed",
        status: null,
        detail: null,
      },
    ],
    itemTypeCounts: {
      commandExecution: 1,
      enteredReviewMode: 1,
      exitedReviewMode: 1,
      fileChange: 1,
      mcpToolCall: 1,
      reasoning: 1,
      subAgentActivity: 1,
      userMessage: 1,
    },
    completedTurns: 2,
    failedTurns: 0,
    truncated: false,
  },
  "demo-thread-hook-audit": {
    id: "demo-thread-hook-audit",
    title: "Audit lifecycle hook coverage",
    status: "notLoaded",
    turns: [
      {
        id: "demo-hook-turn",
        status: "completed",
        startedAt: "2026-08-10T09:12:00Z",
        completedAt: "2026-08-10T09:26:00Z",
        durationMs: 840_000,
        stepCount: 3,
      },
    ],
    steps: [
      {
        id: "demo-hook-request",
        turnId: "demo-hook-turn",
        kind: "userMessage",
        label: "User request",
        status: null,
        detail: null,
      },
      {
        id: "demo-hook-tool",
        turnId: "demo-hook-turn",
        kind: "dynamicToolCall",
        label: "Dynamic tool call",
        status: "completed",
        detail: "Tool: hooks.list",
      },
      {
        id: "demo-hook-message",
        turnId: "demo-hook-turn",
        kind: "agentMessage",
        label: "Agent message",
        status: null,
        detail: null,
      },
    ],
    itemTypeCounts: {
      agentMessage: 1,
      dynamicToolCall: 1,
      userMessage: 1,
    },
    completedTurns: 1,
    failedTurns: 0,
    truncated: false,
  },
};

export function sampleRunDetail(threadId: string): CodexRunDetail | null {
  return sampleRunDetails[threadId] ?? null;
}
